### ISSUE TITLE
Bosses of Mass Destruction Config

### ISSUE THREAD

**Issue by dfeeny1** [ZsoltMolnarrr/PowerScale#28]
Does anyone  know if it is possible to add the bosses of mass destruction to the difficulty/loot scaling of the mod? Mainly this is for the ability to have the items dropped from them scale.

**Comment by ZsoltMolnarrr** [comment]
It is possible to add compatibility.

With the latest release, its really easy.

First find out what is the namespace of their structures (likely "bomd" or something). You can use the `/locate structure` command the figure them out.
Lets say the result they are named like `bmod:some_structure`, `bmod:other_structure`

Knowing this add new zone objects into the config.
```
{
  "zone_matches": {
    "biome": ".*",
    "structure": "bomd:*"
  },
  "difficulty": {
    "name": "dungeon",
    "level": 3
  }
},
```

<img width="780" alt="Screenshot 2024-12-21 at 2 29 16" src="https://github.com/user-attachments/assets/b939b3e8-957e-454b-b55c-1fd77cab1b82" />


For additional discussion, I recommend joining our Discord.

**Comment by dfeeny1** [comment]
THIS WORKS!!!! Thank you so much! I hope this helps other people too. 

The only weird thing we have noticed is that the lich specifically only drops the upgraded loot every other time you fight it. Not sure what that is about but it doesn't really change things for us. Thanks again!

**Comment by Aesthir** [comment]
I believe I know what this is about. Where the lich actually spawns is some random place near the blocks that accept soul stones. Dungeon difficulty only modifies the lich if it spawns within the zone you marked (bosses_of_mass_destruction:lich_tower) yet around half the time the lich spawns outside the lich tower structure.

I haven’t tried this myself, but this work around should solve the issue. Target the entity itself instead of the zone with something like:
```
{
  "entity_matches": {
    "attitude": "ANY",
    "entity_id": "bosses_of_mass_destruction:night_lich"
  },
  "difficulty": {
    "name": "bosses",
    "level": 5
  }
},
```
Ofc, you’d also have to define some characteristics (eg, attributes, rewards, xp, etc…) for the lich in a new difficulty category named “bosses” for this to work. Maybe @ZsoltMolnarrr can tell us if this is possible.
